version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: sa
      MYSQL_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
